# Generated by Django 6.1.1 on 2026-09-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField()),
                ('calving_type', models.CharField(choices=[('Single', 'Single'), ('Twin', 'Twin'), ('Triplets', 'Triplets')], default='Single', max_length=30)),
                ('male_calves', models.PositiveSmallIntegerField(default=0)),
                ('female_calves', models.PositiveSmallIntegerField(default=0)),
                ('complication', models.CharField(choices=[('None', 'None'), ('Mild', 'Mild'), ('Severe', 'Severe'), ('Dead Calf', 'Dead Calf')], default='None', max_length=30)),
                ('vet_name', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calvings', to='herd.animal')),
            ],
            options={
                'ordering': ('-calving_date',),
            },
        ),
        migrations.CreateModel(
            name='Heat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_date', models.DateField()),
                ('expected_heat_date', models.DateField(blank=True, null=True)),
                ('is_bred', models.BooleanField(default=False)),
                ('detected_by', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='herd.animal')),
            ],
            options={
                'ordering': ('-heat_date',),
            },
        ),
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('bull_name', models.CharField(blank=True, default='', max_length=100)),
                ('bull_breed', models.CharField(blank=True, default='', max_length=100)),
                ('semen_source', models.CharField(blank=True, default='', max_length=100)),
                ('technician', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Conceived', 'Conceived'), ('Not Conceived', 'Not Conceived')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminations', to='herd.animal')),
            ],
            options={
                'ordering': ('-service_date',),
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('diagnosis', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unconfirmed', 'Unconfirmed')], default='Unconfirmed', max_length=30)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_checks', to='herd.animal')),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancy_checks', to='breeding.insemination')),
            ],
            options={
                'ordering': ('-check_date',),
            },
        ),
    ]
