# Generated by Django 6.1.1 on 2026-09-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(blank=True, default='', max_length=100)),
                ('origin', models.CharField(blank=True, default='', max_length=100)),
                ('avg_milk_yield', models.DecimalField(decimal_places=2, default=0, help_text='Average litres per day', max_digits=6)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=30, unique=True, verbose_name='Tag number')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Female', max_length=10)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('category', models.CharField(choices=[('Calf', 'Calf'), ('Heifer', 'Heifer'), ('Milker', 'Milker'), ('Dry', 'Dry'), ('Weaner', 'Weaner'), ('Yearling', 'Yearling'), ('Bulling', 'Bulling'), ('Bull', 'Bull'), ('Steer', 'Steer')], default='Heifer', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Culled', 'Culled'), ('Deceased', 'Deceased'), ('Transferred', 'Transferred')], default='Active', max_length=30)),
                ('source', models.CharField(choices=[('Born', 'Born'), ('Purchased', 'Purchased'), ('Transferred In', 'Transferred In')], default='Born', max_length=30)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_dam', to='herd.animal')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_sire', to='herd.animal')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='herd.breed')),
            ],
            options={
                'ordering': ('tag_number',),
            },
        ),
        migrations.CreateModel(
            name='AnimalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('Barn Transfer', 'Barn Transfer'), ('Pasture', 'Pasture'), ('Purchased', 'Purchased'), ('Sold', 'Sold'), ('Transferred Out', 'Transferred Out'), ('Deceased', 'Deceased')], default='Barn Transfer', max_length=30)),
                ('from_location', models.CharField(blank=True, default='', max_length=100)),
                ('to_location', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='herd.animal')),
            ],
            options={
                'ordering': ('-movement_date',),
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status'], name='herd_animal_status_257c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['category'], name='herd_animal_categor_2bc001_idx'),
        ),
    ]
