# Generated by Django 6.1.1 on 2026-09-23 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_daily_liters', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_target', to='herd.animal')),
            ],
            options={
                'verbose_name': 'Yield target',
                'verbose_name_plural': 'Yield targets',
            },
        ),
        migrations.CreateModel(
            name='Lactation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lactation_number', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('dry_off_date', models.DateField(blank=True, null=True)),
                ('expected_dry_off', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactations', to='herd.animal')),
            ],
            options={
                'ordering': ('animal', '-lactation_number'),
                'constraints': [models.UniqueConstraint(fields=('animal', 'lactation_number'), name='unique_lactation_per_animal')],
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='herd.animal')),
            ],
            options={
                'ordering': ('-date', '-session'),
                'constraints': [models.UniqueConstraint(fields=('animal', 'date', 'session'), name='unique_production_per_session')],
            },
        ),
        migrations.CreateModel(
            name='MilkQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fat_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('snf_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('density', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('temperature', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('remarks', models.CharField(blank=True, default='', max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_quality_records', to='herd.animal')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('animal', 'date'), name='unique_quality_per_day')],
            },
        ),
    ]
