# Generated by Django 6.1.1 on 2026-09-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('ship_to', models.CharField(blank=True, default='', max_length=150, verbose_name='Ship to (shop name)')),
                ('driver_name', models.CharField(blank=True, default='', help_text='Auto-filled from the referenced delivery order', max_length=100)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='Sales tax / VAT percentage', max_digits=5, verbose_name='Tax %')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sales.customer')),
                ('delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='deliveries.deliverynote', verbose_name='Delivery order reference no.')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Item code')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice')),
            ],
        ),
    ]
