# Generated by Django 6.1.1 on 2026-09-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Roughage', 'Roughage'), ('Concentrate', 'Concentrate'), ('Mineral', 'Mineral'), ('Silage', 'Silage'), ('Other', 'Other')], default='Other', max_length=30)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('L', 'L'), ('bag', 'bag'), ('tonne', 'tonne'), ('Unit', 'Unit')], default='kg', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FeedConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feeding_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('animal', models.ForeignKey(blank=True, help_text='Leave blank when feeding a herd group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_records', to='herd.animal')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='feed.feeditem')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='feed.feeditem')),
            ],
            options={
                'ordering': ('-purchase_date',),
            },
        ),
    ]
