# Generated by Django 6.1.1 on 2026-09-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Vaccine', 'Vaccine'), ('Antibiotic', 'Antibiotic'), ('Dewormer', 'Dewormer'), ('Vitamin', 'Vitamin'), ('Antiseptic', 'Antiseptic'), ('Other', 'Other')], default='Other', max_length=30)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(default='Dose', max_length=30)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(blank=True, default='', max_length=200)),
                ('treatment_applied', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('veterinarian', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='herd.animal')),
                ('medicines', models.ManyToManyField(blank=True, related_name='treatments', to='health.medicine')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, default='', max_length=50)),
                ('administered_by', models.CharField(blank=True, default='', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='herd.animal')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('findings', models.TextField(blank=True, default='')),
                ('treatment_applied', models.TextField(blank=True, default='')),
                ('vet_name', models.CharField(blank=True, default='', max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visits', to='herd.animal')),
            ],
            options={
                'ordering': ('-visit_date',),
            },
        ),
    ]
