# Generated by Django 6.1.1 on 2026-09-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_order_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Delivery order number')),
                ('your_order_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Your order no.')),
                ('your_order_date', models.DateField(blank=True, null=True, verbose_name='Your order date')),
                ('dispatched_date', models.DateField(blank=True, null=True, verbose_name='Date dispatched')),
                ('driver_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Driver name')),
                ('branch_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Branch name')),
                ('description_of_goods', models.TextField(blank=True, default='Fresh milk delivery', verbose_name='Description of goods')),
                ('qty_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qty delivered (litres)')),
                ('checked_by', models.CharField(blank=True, default='', max_length=100, verbose_name='Checked by')),
                ('supervisor_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Supervisor name')),
                ('supervisor_signed', models.BooleanField(default=False, help_text='Tick when the supervisor has signed', verbose_name='Supervisor signature')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='sales.customer', verbose_name='Customer / To')),
            ],
            options={
                'verbose_name': 'Delivery Note',
                'verbose_name_plural': 'Delivery Notes',
                'ordering': ('-dispatched_date', '-created_at'),
            },
        ),
    ]
